version: "3.8"
services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: application
    container_name: application
    volumes:
      - ./:/app/
    networks:
      - net

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8001:8001
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge